// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/signalai-home/ArticlePage.tsx": () => import("../components/mockups/signalai-home/ArticlePage.tsx"),
  "./components/mockups/signalai-home/Broadsheet.tsx": () => import("../components/mockups/signalai-home/Broadsheet.tsx"),
  "./components/mockups/signalai-home/SignalGrid.tsx": () => import("../components/mockups/signalai-home/SignalGrid.tsx"),
  "./components/mockups/signalai-home/WarmEditorial.tsx": () => import("../components/mockups/signalai-home/WarmEditorial.tsx")
};
